services:
  - type: web
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: "https://frontend-two-black-20.vercel.app"
    buildFilter:
      paths:
        - package.json
        - package-lock.json
        - app.js
        - src/**
